apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob-view-secret-binding
  namespace: prod
subjects:
- kind: User
  name: bob
  apiGroup: ""
roleRef:
  kind: Role
  name: view-secret
  apiGroup: ""