apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob-create-deployment-binding
  namespace: prod
subjects:
- kind: User
  name: bob
  apiGroup: ""
roleRef:
  kind: Role
  name: create-deployment
  apiGroup: ""